### ISSUE TITLE
Pick one of codestyle or pycodestyle

### ISSUE THREAD

**Issue by nils-werner** [henry0312/pytest-pycodestyle#66]
I find it very confusing that

1. the package lives on PyPI under both `pytest-codestyle`, and `pytest-pycodestyle`

2. the GitHub repo is called `pytest-codestyle`
3. the Pytest flag is `--pycodestyle`, and
4. the underlying library is called [`pycodestyle`](https://github.com/PyCQA/pycodestyle)

To mitigate this confusion I would recommend using `pytest-pycodestyle` everywhere.

To that end I'd suggest to

 1. Replace the `pytest-codestyle` package on PyPI with a deprecation dummy package
 2. Rename this repo to `pytest-pycodestyle`

**Comment by henry0312** [comment]
thank you for your suggestion.
those are done.
