### ISSUE TITLE
Work with pytest 6

### ISSUE THREAD

**Issue by impredicative** [henry0312/pytest-pycodestyle#81]
I get the following error when attempting to install `pytest-pycodestyle==2.1.3` with `pytest==6.0.1`:

> ERROR: pytest-pycodestyle 2.1.3 has requirement pytest~=5.4, but you'll have pytest 6.0.1 which is incompatible.

**Comment by bitranox** [comment]
Yeah, just wanted to report the same ... 
also look at the PR, https://github.com/henry0312/pytest-pycodestyle/pull/82
should not be a big deal ...
